# Generated by Django 2.1.11 on 2020-04-12 07:48

import details.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('issuer', models.CharField(max_length=30)),
                ('issue_date', models.DateField()),
                ('association', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_title', models.CharField(max_length=30)),
                ('credential_id', models.CharField(max_length=100)),
                ('credential_url', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('issuing_organization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=7)),
                ('faculty_name', models.CharField(max_length=30, null=True)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(choices=[('CE', 'CE'), ('IT', 'IT'), ('IC', 'IC'), ('CL', 'CL'), ('EC', 'EC'), ('CH', 'CH'), ('MH', 'MH')], default='CE', max_length=2)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(null=True)),
                ('office', models.CharField(max_length=30, null=True)),
                ('biography', models.TextField(null=True)),
                ('specializations', djongo.models.fields.ArrayField(model_container=details.models.Topic, model_form_class=details.models.TopicForm, null=True)),
                ('teaching_interests', djongo.models.fields.ArrayField(model_container=details.models.Topic, null=True)),
                ('faculty_type', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('emp_type', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_currently_working', models.BooleanField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=30)),
                ('publication_date', models.DateField()),
                ('publication_url', models.URLField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('degree', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=100)),
                ('from_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='from year')),
                ('to_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='to year')),
                ('field', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='certification',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.Faculty'),
        ),
        migrations.AddField(
            model_name='award',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Faculty'),
        ),
    ]
